// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/google/wire"
	"github.com/strong-defi/strong-defi-backend/internal/dao"
	"github.com/strong-defi/strong-defi-backend/pkg/db"
	"github.com/strong-defi/strong-defi-backend/pkg/ethereum"
	log2 "github.com/strong-defi/strong-defi-backend/pkg/log"
)

// Injectors from wire.go:

func InitService(logger log2.Logger, config *db.Config, chainConfig *ethereum.Config) (*Service, func(), error) {
	daoDao := dao.New(logger, config, chainConfig)
	etherService := NewEtherService(daoDao)
	stakeService := NewStakeService(daoDao)
	userService := NewUserService(daoDao)
	service := New(logger, etherService, stakeService, userService)
	return service, func() {
	}, nil
}

// wire.go:

// ProviderSet is dao providers.
var ProviderSet = wire.NewSet(New, NewEtherService, NewStakeService, NewUserService)
