server:
  host: 127.0.0.1
  port: '8090'
  adminAddress: "2344dsf"
  deployAddress: "http://127.0.0.1:7545"

mysql:
  dsn : "root:root12345@tcp(127.0.0.1:3306)/sc_stake?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  active : 20   #最大空闲连接数
  idle : 5      #最大打开连接数
  idleTimeout : 4  #单位是小时

logger:
  level: "debug"
  development: true
  encoding: "json"
  output_paths:
    - "stdout"
    - "logs/app.log"
  initial_fields:
    app: "my-service"
    env: "development"
  disable_caller: false
  disable_time: false
  time_format: "2006-01-02 15:04:05.000"
  sampling:
    initial: 100
    thereafter: 10
  file_config:
    max_size: 100
    max_backups: 3
    max_age: 28
    compress: true