server:
  host: 127.0.0.1
  port: '8090'
  adminAddress: "2344dsf"
  deployAddress: "http://127.0.0.1:7545"

mysql:
  dsn : "root:root@tcp(127.0.0.1:3306)/sc_stake?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  active : 20   #最大空闲连接数
  idle : 5      #最大打开连接数
  idleTimeout : 4  #单位是小时

logger:
  level: "debug"
  development: true
  encoding: "json"
  output_paths:
    - "stdout"
    - "logs/app.log"
  initial_fields:
    app: "my-service"
    env: "development"
  disable_caller: false
  disable_time: false
  time_format: "2006-01-02 15:04:05.000"
  sampling:
    initial: 100
    thereafter: 10
  file_config:
    max_size: 100
    max_backups: 3
    max_age: 28
    compress: true

chains:
  ethereum:
    chain_id: 1
    name: "Ethereum Mainnet"
    endpoints:
      - "https://mainnet.infura.io/v3"
      - "https://eth-mainnet.g.alchemy.com/v2"
    api_keys:
      - "your-infura-key"
      - "your-alchemy-key"
    retry:
      max_retries: 3
      retry_delay: 2s
      health_check_interval: 30s
  sepolia:
    chain_id: 11155111
    name: "Sepolia Testnet"
    endpoints:
      - "https://sepolia.infura.io/v3"
      - "https://eth-sepolia.g.alchemy.com/v2"
    api_keys:
      - "your-infura-key"
      - "your-alchemy-key"
    retry:
      max_retries: 3
      retry_delay: 1s
      health_check_interval: 15s
  polygon:
    chain_id: 137
    name: "Polygon Mainnet"
    endpoints:
      - "https://polygon-rpc.com"
      - "https://rpc-mainnet.matic.network"
    retry:
      max_retries: 3
      retry_delay: 1s
      health_check_interval: 15s

  bsc:
    chain_id: 56
    name: "Binance Smart Chain"
    endpoints:
      - "https://bsc-dataseed1.binance.org"
      - "https://bsc-dataseed2.binance.org"
    retry:
      max_retries: 3
      retry_delay: 1s
      health_check_interval: 20s

  arbitrum:
    chain_id: 42161
    name: "Arbitrum One"
    endpoints:
      - "https://arb1.arbitrum.io/rpc"
    api_keys: []
    retry:
      max_retries: 3
      retry_delay: 2s
      health_check_interval: 30s 